# Generated by Django 4.2.6 on 2023-10-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTme', models.DateTimeField()),
                ('Reading', models.IntegerField()),
            ],
        ),
    ]
